### PR TITLE
Adding metadata for models

### PR DESCRIPTION
**Pull request by veekaybee**
See spreadsheet: https://docs.google.com/spreadsheets/d/14vbBbuRMEHoqeuMHkTfw3uiZVmyXNuoSp8s-aHvfvZk/edit#gid=0

### CODE REVIEW

**Comment by veekaybee** [comment]
Let me know what you think of this structure @StellaAthena - I've ported everything except the links to the papers so far.

**Comment by veekaybee** [comment]
Screenshot 2024-01-04 at 11 10 22 AM

**Comment by StellaAthena** [comment]
Can we subcategorize the details? By
1. Data
2. Optimization
3. Architecture

**Comment by veekaybee** [comment]
Sure, which of these do you see going into each category?

```
dataset: "Unreleased"
    tokenizer: "GPT-1"
    training_library: "Unreleased"
    embeddings: "Learned"
    normalization: "LayerNorm"
    parallel_layers: "No"
    biases: "Yes"
    activation_function: "GeLu"
    d_attn_d_ff: 4
    optimizer: "Adam"
    optimizer_hyperparams: "Not Disclosed"
    lr_warmup: ""
    lr_decay: "Cosine to 0"
    precision: "Not Disclosed"
    clipping: "Not Disclosed"
    dropout: 0.1
    weight_decay: Not disclosed
    date: 6/11/2018
    source: "https://cdn.openai.com/research-covers/language-   unsupervised/language_understanding_paper.pdf"
```

**Comment by StellaAthena** [comment]
```
data:
    dataset: "Unreleased"
    tokenizer: "GPT-1"
architecture:
    embeddings: "Learned"
    normalization: "LayerNorm"
    parallel_layers: "No"
    biases: "Yes"
    activation_function: "GeLu"
    d_attn_d_ff: 4
    optimizer: "Adam"
    optimizer_hyperparams: "Not Disclosed"
optimization:
    lr_warmup: ""
    lr_decay: "Cosine to 0"
    precision: "Not Disclosed"
    clipping: "Not Disclosed"
    dropout: 0.1
    weight_decay: Not disclosed
misc:
    training_library: "Unreleased"
    date: 6/11/2018
    source: "https://cdn.openai.com/research-covers/language-   unsupervised/language_understanding_paper.pdf"
```

**Comment by veekaybee** [comment]
Here's the updated table: 
Screenshot 2024-01-10 at 9 12 52 AM

**Comment by StellaAthena** [comment]
It's a good starting point :) thanks for throwing this together.

**Pull request merged**
